[project]
name = "xtsci-optimize"
version = "0.0.1"
description = "Partial SciPy port of optimize using xtensor"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]
license = "MIT"
license-file = "LICENSE"
readme = "readme.org"
repository = "https://github.com/HaoZeke/xtsci-optimize"

[tasks]
lint = {cmd = "pre-commit run --all-files"}

[dependencies]
xtensor-io = "0.13.0.*"
xtensor = "0.24.6.*"
xtensor-blas = "0.20.0.*"
fmt = "10.1.1.*"
scipy = "1.11.2.*"
ipython = "8.15.0.*"
xtensor-python = "0.26.1.*"
catch2 = "3.4.0.*"
zlib = "1.2.13.*"
cppcheck = "2.13.4.*"
cpplint = "1.6.0.*"
pkg-config = "0.29.2.*"
cmake = "3.27.5.*"
ninja = "1.11.1.*"
meson = "1.2.1.*"
numpy = "1.26.0.*"
pip = "23.2.1.*"
matplotlib = "3.3.2.*"
cmcrameri = "1.7.*"
packaging = "23.2.*"
python = "3.9.18.*"
range-v3 = "0.12.0.*"
clang-format = "16.0.1.*"
towncrier = "23.11.0.*"
pre-commit = "3.7.0.*"
