#+TITLE: Constrain an IRC step to the mass-weighted sphere
#+OPTIONS: toc:nil todo:nil num:nil author:nil title:nil
#+STARTUP: content

* Constrain an IRC step to the mass-weighted sphere

The inner Gonzalez--Schlegel / Sella IRC step is not
~ManifoldKind::Sphere~ (the unit sphere about the origin). It is
an equality on ~MwRigid~:

\[
\|(s + d_1)\odot\sqrt{m}\| = dx.
\]

~IrcTrust~ is that restricted step.
~lowest_eigenpair~ is the matrix-free kick (one extremal Hessian
pair from ~H v~, not a full ELPA / SLATE spectrum). The session
that owns forward and reverse branches lives in
[[https://github.com/OmniPotentRPC/rgsaddle][rgsaddle]] (~IrcSession~).

Citations (validated DOIs, also in ~docs/CITATIONS.md~):

- Ishida, Morokuma, Komornicki 1977
  ([[https://doi.org/10.1063/1.434152][10.1063/1.434152]]).
- Page and McIver 1988
  ([[https://doi.org/10.1063/1.454172][10.1063/1.454172]]).
- Gonzalez and Schlegel 1989
  ([[https://doi.org/10.1063/1.456010][10.1063/1.456010]]).
- Hermes, Sarsfield, Zador 2022
  ([[https://doi.org/10.1021/acs.jctc.2c00395][10.1021/acs.jctc.2c00395]]).

** Rust

#+begin_src rust
use ndarray::array;
use rgmin::{lowest_eigenpair, IrcTrust};

let masses = [1.0, 16.0];
let d1 = array![0.1, 0.0, 0.0, 0.0, 0.0, 0.0];
let tr = IrcTrust::from_atom_masses(d1, &masses, 0.2);
let s = array![0.5, 0.1, -0.2, 0.3, 0.0, 0.4];
let p = tr.project(&s);
assert!(tr.on_bound(&p, 1e-12));
#+end_src

The kick uses ~lowest_eigenpair~ on a ~HessianVector~ (analytic
or ~FdHvp~). Default Krylov dimension is small. Do not form the
dense Hessian just to pick the imaginary mode.

** What this is not

- ~ManifoldKind::Sphere~ -- unit \(S^{n-1}\) about 0.
- A full ~heev~ of a 3N Hessian. ELPA / SLATE belong behind
  ~n >= 512~ and a Hessian that already exists. See the rgsaddle
  MEP tutorial.
